### ISSUE TITLE
Makefile:100: *** recipe commences before first target.  Stop.

### ISSUE THREAD

**Issue by marcin-github** [koverstreet/bcachefs-tools#193]
I can't build bcachefs-tools due to error.
```
 make
Makefile:100: *** recipe commences before first target.  Stop.```

first not working commit fbfdd05ac5b5b748cf9c7c0ea72be5268917c5d6
last working commit #5fa7db9806b1f7a082a0bcda8ba7b7beeb03bc61

I use gentoo without systemd.

**Comment by Kangie** [comment]
See also: https://bugs.gentoo.org/919835

https://github.com/koverstreet/bcachefs-tools/blob/4c5dcb018d9675260c056b6afa8508298d0dba75/Makefile#L100

This is not good and probably has never worked, we're only seeing this issue now due to the growing popularity of bcachefs resulting in users building -tools on a variety of filesystems.

Why are we doing this in a makefile?

**Comment by koverstreet** [comment]
The indentation is fixed now - that was just a simple makefile error.
